### ISSUE TITLE
wrong NC version?

### ISSUE THREAD

**Issue by Rello** [pointcz/hidesidebars#2]
Hello,

I like your idea. I was thinking about something like that and even suggesting this to the NC staff already.
I think this opens the possibility for fullscreen apps. (open only one app to a user).

but: are you sure for the NC max version 17 in info.xml?
19 is coming out soon. I think you should raise it...

**Comment by radoslavius** [comment]
Hi,
no, this is wrong. I know about it. I use this "app" in nc 18 with success. I will correct it. For nc 19 I dont know. Someone has to try it...

**Comment by Rello** [comment]
from my experience: put it to NC19 right away. if someone complains, you can still correct.

in my 2 apps, I could not see any difference with 18/19

**Comment by radoslavius** [comment]
Done
