### ISSUE TITLE
apply feature to all apps

### ISSUE THREAD

**Issue by Rello** [pointcz/hidesidebars#3]
Hello,

your app only works in the files-app due to the event listener
https://github.com/pointcz/hidesidebars/blob/master/appinfo/app.php#L4

did you think about removing this dependency, because then it might actually work in all apps which would be very helpful
@MarkPartlett

**Comment by cimbi** [comment]
This could actually be used to create a Desktop app for each app (with [nativefier](https://github.com/jiahaog/nativefier) for example). That would be very useful for everyone! Can I help?

**Comment by radoslavius** [comment]
@Rello @cimbi 
I apologize for the delay. I'm pretty busy. The adjustment was simple and perhaps correct (I hope). The most difficult thing was to find a way to publish the new version.

https://github.com/pointcz/hidesidebars/commit/85918f5382e730618b120facd31375612253fc03
