### ISSUE TITLE
Enable Nextcloud in IFRAME

### ISSUE THREAD

**Issue by ondics** [pointcz/hidesidebars#6]
Did not test this app, but it sounds great. I need Nextcloud to be run in an IFRAME in my application.

Does it solve the problem of Nextcloud rejecting showing up in IFRAMEs?

As far as I understand, Nextcloud has to be patched to make it working in IFRAMEs:
https://www.reddit.com/r/NextCloud/comments/l7eksi/issue_with_iframe/

Since this app is focussing to IFRAME usage, it would be great SAMEORIGIN modifications should be done too.

**Comment by radoslavius** [comment]
In new version of app (2.0.0), I added new parameter for config.php `addAllowedFrameAncestorDomain` ;)
