### ISSUE TITLE
Hide sidebars on public links

### ISSUE THREAD

**Issue by cyrzero** [pointcz/hidesidebars#7]
Hello, 
I'm on version 23.0.6 
And you application donesn't work on public links, I try to use  :
 _.../s/EwKjigzYdgbdd?hide-sidebars_ # don't hide bars
_.../s/EwKjigzYdgbdd&hide-sidebars_ # nextcloud can't find the share

But if i try whit an account it works...

**Comment by radoslavius** [comment]
Try new version 2.1.0
