### ISSUE TITLE
Does not work with Nextcloud talk

### ISSUE THREAD

**Issue by fbartels** [pointcz/hidesidebars#8]
Hi,

I've stumbled upon your plugin, but I've noticed that it does not seem to have an effect on Nextcloud Talk. Since a [previous issue](https://github.com/pointcz/hidesidebars/issues/3)  stated that the plugin should work with all apps in Nextcloud I wanted to let you know.

Nextcloud: 24.0.02
Talk: 14.0.3
Hide Sidebars 2.1.0

**Comment by radoslavius** [comment]
I use Nextcloud only for working with files and I insert it into our crm using iframes. I've looked into it, but I don't have a quick solution. Unfortunately I don't have time to solve the sidebars hiding in the other plugins. If someone finds a solution, I will gladly incorporate it into the code and publish it.
