### ISSUE TITLE
Does not work with other apps except files anymore (like Calendar or Deck)

### ISSUE THREAD

**Issue by fenglisch** [pointcz/hidesidebars#9]
I remember that this app used to work not only with files, but also with apps like Nextcloud Decks. This seems to be the result of issue https://github.com/pointcz/hidesidebars/issues/3

However, this doesn't work anymore with Nextcloud version 21. The commit https://github.com/pointcz/hidesidebars/commit/85918f5382e730618b120facd31375612253fc03 says "set max version to 20". Maybe this is the reason?

**Comment by radoslavius** [comment]
Hi, nextcloud version up to 22 is unsupported at this time. The actual version of hidesidebars is 2... and should be working from the version 21. I suggest to upgrade nextcloud to the current stable version.

**Comment by fenglisch** [comment]
Thanks for your quick response, @radoslavius . The app indeed works with Nextcloud version 21 in general, but only with the files & folders and not in other apps (at least not on both of my clouds and with the apps I tested). `https://cloud.domain.tld/apps/deck/#/board/1234&hide-sidebars` (Kanban app "Decks") used to work, but it does not anymore. Am I doing something wrong? Or is this due to the Deck app and not the Hide Sidebars app? Does the Hide Sidebars app work with other apps?

**Comment by drumdum** [comment]
I stumbled upon this great app and tested it. I'm on Nextcloud 24, using hide-sidebars 2.1.0 and the only app it works with is Files, exactly as @fenglisch discovered, unfortunately. It would be awesome if it could be used with any app from Nextcloud. Is there anything I need to set up correctly?

When trying https://cloud.domain.tld/apps/deck/?hide-sidebars gets https://cloud.domain.tld/apps/deck/?hide-sidebars#/, but the sidebars are still there.

**Comment by radoslavius** [comment]
I use Nextcloud only for working with files and I insert it into our crm using iframes. I've looked into it, but I don't have a quick solution. Unfortunately I don't have time to solve the sidebars hiding in the other plugins. If someone finds a solution, I will gladly incorporate it into the code and publish it.
